ntr/urls.py
from django.urls import path

from ntr.views import *

app_name='ntr'

urlpatterns=[
    path('temper/',temper,name='temper'),
    path('aadhi/',aadhi,name='aadhi'),
]

project16/urls.py
from django.contrib import admin
from django.urls import path,include
from rc.views import *
from aa.views import *
import ntr

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ntr/',include('ntr.urls')),
    path('dhruva/',dhruva,name='dhruva'),
    path('chirutha/',chirutha,name='chirutha'),
    path('aarya/',aarya,name='aarya'),
    path('bunny/',bunny,name='bunny'),
]

aa/models.py
from django.db import models

# Create your models here.

ntr/models.py
from django.db import models

# Create your models here.

rc/models.py
from django.db import models

# Create your models here.

aa/views.py
from django.shortcuts import render

# Create your views here.

def aarya(request):
    return render(request,'aarya.html')

def bunny(request):
    return render(request,'bunny.html')

ntr/views.py
from django.shortcuts import render

# Create your views here.

def temper(request):
    return render(request,'temper.html')

def aadhi(request):
    return render(request,'aadhi.html')

rc/views.py
from django.shortcuts import render

# Create your views here.

def dhruva(request):
    return render(request,'dhruva.html')

def chirutha(request):
    return render(request,'chirutha.html')

templates/aadhi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="background-color: violet;">
    <center>
        <h1 style="background-color: indigo; colour: red">AADHI</h1>
    </center>
    <h1>Aadi is a 2002 Indian Telugu-language action drama film written and directed by debutant V. V. Vinayak. The film stars N. T. Rama Rao Jr. and Keerthi Chawla. The film was a huge commercial success and was remade in Tamil as Jai and in Bengali as Surya. The film won four Nandi Awards and was released in 118 centres and ran for 100 days in 96 centres.[1]</h1>
    <center style="color: rgb(255, 136, 0);">
        <h1><a href="{% url 'ntr:temper' %}">go to temper</a></h1>
        <h1><a href="{% url 'aarya' %}">go to aarya </a></h1>
        <h1><a href="{% url 'bunny' %}">go to bunny</a></h1>
        <h1><a href="{% url 'chirutha' %}">go to chirutha</a></h1>
        <h1><a href="{% url 'dhruva' %}">go to dhruva</a></h1>
    </center>
</body>
</html>

templates/aarya.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="background-color: indigo:">
    <center>
        <h1 style="background-color: green; color:gold">AARYA</h1>
    </center>
    <h1 style="color: rgb(247, 79, 13);">Arya is a 2004 Indian Telugu-language romantic action film written and directed by debutant Sukumar. Produced by Dil Raju under Sri Venkateswara Creations banner, the film stars Allu Arjun, Anu Mehta, and Siva Balaji. The music is composed by Devi Sri Prasad and cinematography is handled by R. Rathnavelu. The plot revolves around Aarya, an outgoing and free-spirited boy falling in love with Geetha, an introverted girl who is on the shield of another person Ajay.</h1>
    <center>
        <h1><a href="{% url 'ntr:aadhi' %}">go to aadhi</a></h1>
        <h1><a href="{% url 'chirutha' %}">go to chirutha</a></h1>
        <h1><a href="{% url 'bunny' %}">go to bunny</a></h1>
        <h1><a href="{% url 'dhruva' %}">go to dhruva</a></h1>
        <h1><a href="{% url 'ntr:temper' %}">go to temper</a></h1>
    </center>
</body>
</html>

templates/bunny.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="background-color: blue;">
    <center>
        <h1 style="background-color: gold;">BUNNY</h1>
    </center>
    <h1 style="color: white;">Bunny is a 2005 Indian Telugu-language action film written and directed by V. V. Vinayak, with cinematography by Chota K. Naidu. The film was produced by Mallidi Satyanarayana Reddy. This film stars Allu Arjun and Gowri Munjal, while Prakash Raj and Mukesh Rishi play supporting roles with Sarath Kumar in a guest appearance. The music was composed by Devi Sri Prasad with editing done by Gautham Raju and cinematography by Chota K. Naidu. The film released on 6 April 2005 and was commercially successful.</h1>
    <center>
        <h1><a href="{% url 'ntr:aadhi' %}">go to aadhi</a></h1>
        <h1><a href="{% url 'chirutha' %}">go to chirutha</a></h1>
        <h1><a href="{% url 'aarya' %}">go to aarya</a></h1>
        <h1><a href="{% url 'dhruva' %}">go to dhruva</a></h1>
        <h1><a href="{% url 'ntr:temper' %}">go to temper</a></h1>
    </center>
</body>
</html>

templates/chirutha.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="background-color: greenyellow;">
    <center>
        <h1 style="background-color: red; color:white">CHIRUTHA</h1>
    </center>
    <h1>Chirutha (transl. Cheetah) is a 2007 Indian Telugu-language action film written and directed by Puri Jagannadh, and produced by C. Ashwini Dutt under the banner Vyjayanthi Movies. The film stars Ram Charan, Neha Sharma, Prakash Raj and Ashish Vidyarthi while Tanikella Bharani, Sayaji Shinde, Daniel Balaji and Brahmanandam play supporting roles. Ram Charan and Neha Sharma make their debuts. The film revolves around Charan, a young man in pursuit of a gangster who murdered his parents.</h1>
    <center>
        <h1><a href="{% url 'ntr:aadhi' %}">go to aadhi</a></h1>
        <h1><a href="{% url 'aarya' %}">go to aarya</a></h1>
        <h1><a href="{% url 'bunny' %}">go to bunny</a></h1>
        <h1><a href="{% url 'dhruva' %}">go to dhruva</a></h1>
        <h1><a href="{% url 'ntr:temper' %}">go to temper</a></h1>
    </center>
</body>
</html>

templates/dhruva.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="background-color: yellow;">
    <center>
        <h1 style="background-color: red;">DHRUVA</h1>
    </center>
    <h1 style="color: blue;">Dhruva is a 2016 Indian Telugu-language action thriller film[3] directed by Surender Reddy and produced by Allu Aravind under his banner Geetha Arts. It features Ram Charan in the titular role, along with Aravind Swamy, Rakul Preet Singh, and Navdeep in important roles. A remake of the Tamil film Thani Oruvan (2015), it follows Dhruva, an IPS officer who wants to arrest Siddharth Abhimanyu, a wealthy scientist, who uses secret medical and illegal practices for profit.[4]</h1>
    <center>
        <h1><a href="{% url 'ntr:aadhi' %}">go to aadhi</a></h1>
        <h1><a href="{% url 'aarya' %}">go to aarya</a></h1>
        <h1><a href="{% url 'bunny' %}">go to bunny</a></h1>
        <h1><a href="{% url 'chirutha' %}">go to chirutha</a></h1>
        <h1><a href="{% url 'ntr:temper' %}">go to temper</a></h1>
    </center>
</body>
</html>

templates/temper.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="background-color: orange;">
    <center>
        <h1 style="background-color: brown; color:orange">TEMPER</h1>
    </center>
    <h1 style="background-color: pink;">Temper is a 2015 Indian Telugu-language action film written by Vakkantham Vamsi and directed by Puri Jagannadh. Starring N. T. Rama Rao Jr., Kajal Aggarwal and Prakash Raj, the narrative revolves around Daya, a corrupt police officer, whose life changes after a brawl that eventually leads to him stumbling upon a murder case.</h1>
    <center>
        <h1><a href="{% url 'ntr:aadhi' %}">go to aadhi</a></h1>
        <h1><a href="{% url 'aarya' %}">go to aarya</a></h1>
        <h1><a href="{% url 'bunny' %}">go to bunny</a></h1>
        <h1><a href="{% url 'chirutha' %}">go to chirutha</a></h1>
        <h1><a href="{% url 'dhruva' %}">go to dhruva</a></h1>
    </center>
</body>
</html>